export const PREVIEW = {
  AMBIENT_LIGHT_COLOR: 0xffffff,
  AMBIENT_LIGHT_INTENSITY: 0.5,
  DIRECTIONAL_LIGHT_COLOR: 0xffffff,
  DIRECTIONAL_LIGHT_INTENSITY: 1,
  DIRECTIONAL_LIGHT_POS_X: 0,
  DIRECTIONAL_LIGHT_POS_Y: 10,
  DIRECTIONAL_LIGHT_POS_Z: 5,

  BACKGROUND_COLOR_LIGHT: 0xf2f0ea,

  CAMERA_FOV: 40,
  CAMERA_NEAR_PLANE: 0.1,
  CAMERA_FAR_PLANE: 100,
  CAMERA_START_Y: 2,
  CAMERA_START_Z: 2,

  GRID_SIZE: 5,
  GRID_DIVISION: 15,

  SHADOW_OPACITY: 0.3,
  SHADOW_PLANE_ROTATION_X: -Math.PI / 2,
  SHADOW_PLANE_Y_OFFSET: 0.01,
  SHADOW_MAP_SIZE: 2048,
};
